### ISSUE TITLE
Entity Relationship Diagram

### ISSUE THREAD

**Issue by patoyrey** [patoyrey/lms#1]

**Comment by Hydro012001** [comment]
![Image](https://github.com/patoyrey/lms/assets/76999604/d550179c-c2c0-4e3d-8d52-933a66a5abb7)

**Comment by patoyrey** [comment]
Add new Table "Doctor"
with this corresponding fields:


![Image](https://github.com/patoyrey/lms/assets/116054641/0539e674-8baf-49ad-808c-0cbc6f76b13a)

**Comment by patoyrey** [comment]
add "Admin", "Nurse" table with basic fields

**Comment by patoyrey** [comment]
![Image](https://github.com/patoyrey/lms/assets/116054641/bc28bc0a-ca18-4058-ad15-eb2fca7fd6ec)

add "Status", "UserType" fields

**Comment by Hydro012001** [comment]
![Image](https://github.com/patoyrey/lms/assets/76999604/5746cac0-b038-4ff0-be6e-0a018b6e9926)

**Comment by patoyrey** [comment]
DB_NAME="LMS"
HOST="localhost"
USER="root"
PASSWORD=""
